version: '3.8'
services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sql-server
    environment:
      - ConnectionStrings__RockPaperScissors=Server=sql-server,1433;Database=RockPaperScissors;User Id=sa;Password=${SA_PASSWORD}
    networks:
      - app-network
    entrypoint: ["sh", "-c", "dotnet ef database update && dotnet RockPaperScissors.Api.dll"]

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    networks:
      - app-network
    volumes:
      - sql-data:/var/opt/mssql

networks:
  app-network:
    driver: bridge

volumes:
  sql-data:
    driver: local
